#!/bin/bash
python3 -m pip install --upgrade build
python3 -m build
python3 -m pip install --upgrade twine
# twine upload -u __token__ -p 'MUST MODIFY YOUR TOKEN HERE' --repository-url https://upload.pypi.org/legacy/ dist/*
